OpenBankProject/API-Manager

apimanager/apimanager/settings.py, apimanager/base/context_processors.py, apimanager/base/templates/base.html, apimanager/users/urls.py, apimanager/users/views.py
=> Added a new tab Users -> My User which shows data for currently logged user

apimanager/apimanager/settings.py, apimanager/apimanager/urls.py, apimanager/base/filters.py, apimanager/base/templates/base.html, apimanager/entitlementrequests/apps.py, apimanager/entitlementrequests/static/entitlementrequests/css/entitlementrequests.css, apimanager/entitlementrequests/static/entitlementrequests/js/entitlementrequests.js, apimanager/entitlementrequests/templates/entitlementrequests/includes/filter_time.html, apimanager/entitlementrequests/templates/entitlementrequests/index.html, apimanager/entitlementrequests/urls.py, apimanager/entitlementrequests/views.py
=> Added Entitlement Requests

apimanager/metrics/templates/metrics/api.html, apimanager/metrics/views.py
@simonredfern Please consider the change
=> Get Metrics issue fixed

apimanager/users/templates/users/includes/filter_role.html, apimanager/users/templates/users/includes/filter_username.html, apimanager/users/templates/users/index.html, apimanager/users/views.py
=> Added filtering by username

apimanager/base/static/css/base.css, apimanager/metrics/templates/metrics/api.html
Added Duration column to metrics
=> Added Duration column to metrics

apimanager/consumers/forms.py, apimanager/consumers/templates/consumers/detail.html, apimanager/consumers/views.py
Show the five call limits value on detail view
Fix the "/consumers" api again
Set the consumer_id to a hidden input in the Consumers detail view
=>  Show the five call limits value on consumer detail view

apimanager/consumers/forms.py, apimanager/metrics/views.py, apimanager/users/templates/users/includes/filter_pagination.html, apimanager/users/templates/users/index.html, apimanager/users/views.py, requirements.txt
Fix the datetime problem in "KPI Dashboard" of "Metrics" and optimized the code, And You need set 
"API_DATEFORMAT = '%Y-%m-%dT%H:%M:%S.000Z'" in your "/apimanager/apimanager/local_settings.py"
=> Fix the datetime problem in "KPI Dashboard" of "Metrics"

apimanager/metrics/views.py
Issue #65 fixed
fix local_settings to settings
=> Error handling for KPI Dashboard of API Manager #65

apimanager/apimanager/settings.py, apimanager/apimanager/urls.py, apimanager/base/context_processors.py, apimanager/base/templates/base.html, apimanager/consumers/views.py, apimanager/entitlementrequests/views.py, apimanager/metrics/views.py, apimanager/obp/api.py, apimanager/obp/oauth.py, apimanager/users/views.py
=>  Change Customer menu item to Resources which is a drop down menu 

apimanager/apimanager/settings.py, apimanager/apimanager/urls.py, apimanager/base/templates/base.html, apimanager/branches/forms.py, apimanager/branches/static/branches/css/branches.css, apimanager/branches/static/branches/js/branches.js, apimanager/branches/templates/branches/index.html, apimanager/branches/templates/branches/update.html, apimanager/branches/urls.py, apimanager/entitlementrequests/views.py, apimanager/obp/api.py, apimanager/obp/oauth.py, apimanager/users/apps.py, apimanager/users/views.py
user None exception in users\views
verify warnings to check if start with https
=> https://github.com/OpenBankProject/API-Manager/pull/67

apimanager/branches/admin.py, apimanager/branches/apps.py, apimanager/branches/forms.py, apimanager/branches/models.py, apimanager/branches/tests.py, apimanager/branches/views.py
=> Add branches

apimanager/branches/templates/branches/index.html, apimanager/branches/templates/branches/update.html, apimanager/branches/views.py
=> branch update api

apimanager/consumers/views.py, apimanager/obp/directlogin.py, apimanager/users/views.py
=> Throw 500 error, when grant some roles to some users #83

apimanager/methodrouting/templates/methodrouting/index.html
=> Add stored_procedure_vDec2019 connector

apimanager/consumers/views.py, apimanager/entitlementrequests/views.py
=> Improve error handling

apimanager/methodrouting/views.py, apimanager/metrics/forms.py, apimanager/metrics/templates/metrics/api.html, apimanager/metrics/templates/metrics/connector.html, apimanager/metrics/views.py
start_date--> from_date and end_date --> to_date
=> bugfix/fixed metrics endpoints wrong parameters  

apimanager/obp/oauth.py
=> Fix SSO redirects to the portal instead of apis side

apimanager/apimanager/settings.py, apimanager/base/static/css/base.css, apimanager/base/templates/base.html, apimanager/base/templates/home.html, apimanager/base/views.py
=> Re-brand API Manager - LOGO

apimanager/apimanager/settings.py, apimanager/base/context_processors.py, apimanager/base/templates/base.html, apimanager/base/views.py
@simonredfern Please consider the changes
=> Re-brand API Manager

apimanager/base/static/css/override.css, apimanager/base/templates/base.html
=> Fix highlighting at the nenu item Users

apimanager/users/forms.py
=> Make all fileds mandatory at User invitation page

apimanager/users/views.py
=> feature/Add field last_marketing_agreement_signed_date to CSV export

apimanager/base/context_processors.py
=> Enhance function api_usernamre in order to handle Azure
